use `The Heathens Store`;

INSERT INTO nations (name, code) VALUES 
('Afghanistan', 'AFG'), ('Australia', 'AUS'), ('Bahrain', 'BHR'), ('Bangladesh', 'BAN'), ('Bhutan', 'BHU'), ('Brunei', 'BRU'), ('Cambodia', 'CAM'), ('China', 'CHN'), ('Guam', 'GUM'), ('Hong Kong', 'HKG'), ('India', 'IND'), ('Indonesia', 'IDN'), ('Iran', 'IRN'), ('Iraq', 'IRQ'), ('Japan', 'JPN'), ('Jordan', 'JOR'), ('Kuwait', 'KUW'), ('Kyrgyzstan', 'KGZ'), ('Laos', 'LAO'), ('Lebanon', 'LBN'), ('Macau', 'MAC'), ('Malaysia', 'MAS'), ('Maldives', 'MDV'), ('Mongolia', 'MNG'), ('Myanmar', 'MYA'), ('Nepal', 'NEP'), ('North Korea', 'PRK'), ('Oman', 'OMA'), ('Pakistan', 'PAK'), ('Palestine', 'PLE'), ('Philippines', 'PHI'), ('Qatar', 'QAT'), ('Saudi Arabia', 'KSA'), ('Singapore', 'SGP'), ('South Korea', 'KOR'), ('Sri Lanka', 'SRI'), ('Syria', 'SYR'), ('Taiwan', 'TPE'), ('Tajikistan', 'TJK'), ('Thailand', 'THA'), ('East Timor', 'TLS'), ('Turkmenistan', 'TKM'), ('United Arab Emirates', 'UAE'), ('Uzbekistan', 'UZB'), ('Vietnam', 'VNM'), ('Yemen', 'YEM'), ('Northern Mariana Islands', 'NMI'),('Albania', 'ALB'), ('Andorra', 'AND'), ('Armenia', 'ARM'), ('Austria', 'AUT'), ('Azerbaijan', 'AZE'), ('Belarus', 'BLR'), ('Belgium', 'BEL'), ('Bosnia and Herzegovina', 'BIH'), ('Bulgaria', 'BUL'), ('Croatia', 'CRO'), ('Cyprus', 'CYP'), ('Czech Republic', 'CZE'), ('Denmark', 'DEN'), ('England', 'ENG'), ('Estonia', 'EST'), ('Faroe Islands', 'FRO'), ('Finland', 'FIN'), ('France', 'FRA'), ('Georgia', 'GEO'), ('Germany', 'GER'), ('Gibraltar', 'GIB'), ('Greece', 'GRE'), ('Hungary', 'HUN'), ('Iceland', 'ISL'), ('Ireland', 'IRL'), ('Israel', 'ISR'), ('Italy', 'ITA'), ('Kazakhstan', 'KAZ'), ('Kosovo', 'KOS'), ('Latvia', 'LVA'), ('Liechtenstein', 'LIE'), ('Lithuania', 'LTU'), ('Luxembourg', 'LUX'), ('Malta', 'MLT'), ('Moldova', 'MDA'), ('Montenegro', 'MNE'), ('Netherlands', 'NED'), ('North Macedonia', 'MKD'), ('Northern Ireland', 'NIR'), ('Norway', 'NOR'), ('Poland', 'POL'), ('Portugal', 'POR'), ('Romania', 'ROU'), ('Russia', 'RUS'), ('San Marino', 'SMR'), ('Scotland', 'SCO'), ('Serbia', 'SRB'), ('Slovakia', 'SVK'), ('Slovenia', 'SVN'), ('Spain', 'ESP'), ('Sweden', 'SWE'), ('Switzerland', 'SUI'), ('Turkey', 'TUR'), ('Ukraine', 'UKR'), ('Wales', 'WAL'),
('Algeria', 'ALG'), ('Angola', 'ANG'), ('Benin', 'BEN'), ('Botswana', 'BOT'), ('Burkina Faso', 'BFA'), ('Burundi', 'BDI'), ('Cameroon', 'CMR'), ('Cape Verde', 'CPV'), ('Central African Republic', 'CTA'), ('Chad', 'CHA'), ('Comoros', 'COM'), ('Congo', 'CGO'), ('DR Congo', 'COD'), ('Djibouti', 'DJI'), ('Egypt', 'EGY'), ('Equatorial Guinea', 'EQG'), ('Eritrea', 'ERI'), ('Eswatini', 'SWZ'), ('Ethiopia', 'ETH'), ('Gabon', 'GAB'), ('Gambia', 'GAM'), ('Ghana', 'GHA'), ('Guinea', 'GUI'), ('Guinea-Bissau', 'GNB'), ('Ivory Coast', 'CIV'), ('Kenya', 'KEN'), ('Lesotho', 'LES'), ('Liberia', 'LBR'), ('Libya', 'LBY'), ('Madagascar', 'MAD'), ('Malawi', 'MAW'), ('Mali', 'MLI'), ('Mauritania', 'MTN'), ('Mauritius', 'MRI'), ('Morocco', 'MAR'), ('Mozambique', 'MOZ'), ('Namibia', 'NAM'), ('Niger', 'NIG'), ('Nigeria', 'NGA'), ('Rwanda', 'RWA'), ('Sao Tome and Principe', 'STP'), ('Senegal', 'SEN'), ('Seychelles', 'SEY'), ('Sierra Leone', 'SLE'), ('Somalia', 'SOM'), ('South Africa', 'RSA'), ('South Sudan', 'SSD'), ('Sudan', 'SUD'), ('Tanzania', 'TAN'), ('Togo', 'TOG'), ('Tunisia', 'TUN'), ('Uganda', 'UGA'), ('Zambia', 'ZAM'), ('Zimbabwe', 'ZIM'),
('Anguilla', 'AIA'), ('Antigua and Barbuda', 'ATG'), ('Aruba', 'ARU'), ('Bahamas', 'BAH'), ('Barbados', 'BRB'), ('Belize', 'BLZ'), ('Bermuda', 'BER'), ('British Virgin Islands', 'VGB'), ('Canada', 'CAN'), ('Cayman Islands', 'CAY'), ('Costa Rica', 'CRC'), ('Cuba', 'CUB'), ('Curacao', 'CUW'), ('Dominica', 'DMA'), ('Dominican Republic', 'DOM'), ('El Salvador', 'SLV'), ('Grenada', 'GRN'), ('Guatemala', 'GUA'), ('Guyana', 'GUY'), ('Haiti', 'HAI'), ('Honduras', 'HON'), ('Jamaica', 'JAM'), ('Mexico', 'MEX'), ('Montserrat', 'MSR'), ('Nicaragua', 'NCA'), ('Panama', 'PAN'), ('Puerto Rico', 'PUR'), ('Saint Kitts and Nevis', 'SKN'), ('Saint Lucia', 'LCA'), ('Saint Vincent and the Grenadines', 'VIN'), ('Suriname', 'SUR'), ('Trinidad and Tobago', 'TRI'), ('Turks and Caicos Islands', 'TCA'), ('USA', 'USA'), ('US Virgin Islands', 'VIR'),
('Argentina', 'ARG'), ('Bolivia', 'BOL'), ('Brazil', 'BRA'), ('Chile', 'CHI'), ('Colombia', 'COL'), ('Ecuador', 'ECU'), ('Paraguay', 'PAR'), ('Peru', 'PER'), ('Uruguay', 'URU'), ('Venezuela', 'VEN'),
('American Samoa', 'ASA'), ('Cook Islands', 'COK'), ('Fiji', 'FIJ'), ('New Caledonia', 'NCL'), ('New Zealand', 'NZL'), ('Papua New Guinea', 'PNG'), ('Samoa', 'SAM'), ('Solomon Islands', 'SOL'), ('Tahiti', 'TAH'), ('Tonga', 'TGA'), ('Vanuatu', 'VAN');





