spring.application.name=TheHeathensStore
management.endpoints.web.exposure.include=*
spring.main.web-application-type=servlet

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.allow_update_outside_transaction=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#spring.jpa.properties.hibernate.current_session_context_class=thread
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.thymeleaf.cache=false
spring.web.resources.cache.cachecontrol.max-age=0
spring.web.resources.chain.cache=false
server.port=8080